name: release

on:
  release:
    types: ['published']

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update version
      run: |
        PRODUCT_SETTINGS_PATH=./YPaste/Info.plist
        version=$(git describe --tags `git rev-list --tags --max-count=1`)
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $version" $PRODUCT_SETTINGS_PATH

    - name: install depencies
      run: pod install
    - name: archive
      run: xcodebuild archive -workspace YPaste.xcworkspace -scheme YPaste -archivePath ./archive-YPaste -configuration Release
    - name: copy app && zip app && generate appcast
      env:
        sparkle_key: ${{ secrets.sparkle_key }}
      run: |
        mkdir apps
        cp -a ./archive-YPaste.xcarchive/Products/Applications/*.app apps
        ditto -c -k --sequesterRsrc --keepParent apps/YPaste.app apps/YPaste.zip
        # rm -r ~/Library/Caches/Sparkle_generate_appcast/*
        ./bin/generate_appcast -s $sparkle_key ./apps/
        c=$(cat ./apps/appcast.xml)
        echo $c | sed -e "s/url[^ ]*/url=\"https:\/\/github.com\/qwertyyb\/YPaste\/releases\/latest\/download\/YPaste.zip\"/g" > apps/appcast.xml

    - name: upload release file
      uses: AButler/upload-release-assets@v1.0
      with:
        files: 'apps/YPaste.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: upload artifact
      with:
        name: appcast
        path: ./apps/appcast.xml

  commit:
    needs: build
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1

    - name: download artifact
      with:
        name: appcast

    - name: commit appcast.xml
      uses: EndBug/add-and-commit@v2.1.0 
      with:
        author_name: appcast updater
        author_email: qwertyyb@foxmail.com
        message: "release: update version"
        path: "appcast.xml"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
