name: release

on:
  release:
    types: ['published']

jobs:
  release:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update version
      run: |
        PRODUCT_SETTINGS_PATH=./YPaste/Info.plist
        version=$(git describe --tags `git rev-list --tags --max-count=1`)
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $version" $PRODUCT_SETTINGS_PATH

    - name: install depencies
      run: pod install
    - name: archive
      run: xcodebuild archive -workspace YPaste.xcworkspace -scheme YPaste -archivePath ./archive-YPaste -configuration Release
    - name: copy app && zip app && generate appcast
      env:
        sparkle_key: ${{ secrets.sparkle_key }}
      run: |
        mkdir apps
        cp -a ./archive-YPaste.xcarchive/Products/Applications/*.app apps
        ditto -c -k --sequesterRsrc --keepParent apps/YPaste.app apps/YPaste.zip
        # rm -r ~/Library/Caches/Sparkle_generate_appcast/*
        ./bin/generate_appcast -s $sparkle_key ./apps/

    - name: release
      uses: AButler/upload-release-assets@v1.0
      with:
        files: 'apps/YPaste.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: install & config coscmd
      env:
        oss_appid: ${{ secrets.oss_appid }}
        oss_secret: ${{ secrets.oss_secret }}
      run: |
        pip install pip==9.0.0 && pip install coscmd
        coscmd config -a $oss_appid -s $oss_secret -b person-1253524658 -r ap-beijing
    - name: upload app and appcast
      run: |
        coscmd upload ./apps/YPaste.zip cloudfn/YPaste.zip
        coscmd upload ./apps/appcast.xml cloudfn/appcast.xml
