name: release

on:
  release:
    types: ['published']

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update version
      run: |
        PRODUCT_SETTINGS_PATH=./YPaste/Info.plist
        version=$(git describe --tags `git rev-list --tags --max-count=1`)
        /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $version" $PRODUCT_SETTINGS_PATH

    - name: install depencies
      run: pod install
    - name: archive
      run: xcodebuild archive -workspace YPaste.xcworkspace -scheme YPaste -archivePath ./archive-YPaste -configuration Release
    - name: copy app && zip app && generate appcast
      env:
        sparkle_key: ${{ secrets.sparkle_key }}
      run: |
        mkdir apps
        cp -a ./archive-YPaste.xcarchive/Products/Applications/*.app apps
        ditto -c -k --sequesterRsrc --keepParent apps/YPaste.app apps/YPaste.zip
        # rm -r ~/Library/Caches/Sparkle_generate_appcast/*
        ./bin/generate_appcast -s $sparkle_key ./apps/
        c=$(cat ./apps/appcast.xml)
        echo $c | sed -e "s/url[^ ]*/url=\"https:\/\/github.com\/qwertyyb\/YPaste\/releases\/latest\/download\/YPaste.zip\"/g" > apps/appcast.xml

    - name: upload release file
      uses: AButler/upload-release-assets@v1.0
      with:
        files: 'apps/YPaste.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/upload-artifact@v1
      with:
        name: appcast
        path: ./apps/appcast.xml

  commit:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v1

    - name: switch master branch
      run: git checkout master

    - uses: actions/download-artifact@v1
      with:
        name: appcast

    - name: move appcast.xml
      run: |
        mv appcast/appcast.xml ./appcast.xml
        rm -rf appcast

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update version"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

