name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install depencies
      run: pod install
    - name: archive
      run: xcodebuild archive -workspace YPaste.xcworkspace -scheme YPaste -archivePath ./archive-YPaste -configuration Release
    - name: copy app && zip app && generate appcast
      env:
        sparkle_key: ${{ secrets.sparkle_key }}
      run: |
        mkdir apps
        cp -a ./archive-YPaste.xcarchive/Products/Applications/*.app apps
        ditto -c -k --sequesterRsrc --keepParent apps/YPaste.app apps/YPaste.zip
        # rm -r ~/Library/Caches/Sparkle_generate_appcast/*
        ./bin/generate_appcast -s $sparkle_key ./apps/
