name: test

on:
  pull_request:
    branch:
      - "**"

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: apple-actions/import-codesign-certs@v1
      with: 
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - name: install depencies
      run: pod install
    - name: archive
      run: |
      xcodebuild archive -workspace YPaste.xcworkspace -scheme YPaste -archivePath ./archive-YPaste -configuration Release
      echo "export archive"
      /usr/bin/xcodebuild -exportArchive -archivePath ./archive-YPaste.xcarchive -exportOptionsPlist "./scripts/ExportOptions.plist" -exportPath ./apps/ || { echo "Export Archive Failed : xcodebuild exportArchive action failed"; exit 1; }
    - name: copy app && zip app && generate appcast
      env:
        sparkle_key: ${{ secrets.sparkle_key }}
      run: |
        mkdir apps
        cp -a ./archive-YPaste.xcarchive/Products/Applications/*.app apps
        ditto -c -k --sequesterRsrc --keepParent apps/YPaste.app apps/YPaste.zip
        # rm -r ~/Library/Caches/Sparkle_generate_appcast/*
        ./bin/generate_appcast -s $sparkle_key ./apps/
